"""add history source fields

Revision ID: 7b27e4ed97cd
Revises: 7dc38e7ab782
Create Date: 2025-08-30 18:15:25.551979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b27e4ed97cd'
down_revision = '7dc38e7ab782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 检查并添加来源字段
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    history_columns = [col['name'] for col in inspector.get_columns('history')]
    
    with op.batch_alter_table('history', schema=None) as batch_op:
        if 'source_url' not in history_columns:
            batch_op.add_column(sa.Column('source_url', sa.String(length=512), nullable=True))
        if 'source_title' not in history_columns:
            batch_op.add_column(sa.Column('source_title', sa.String(length=256), nullable=True))
        if 'source_type' not in history_columns:
            batch_op.add_column(sa.Column('source_type', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_column('source_type')
        batch_op.drop_column('source_title')
        batch_op.drop_column('source_url')
    # ### end Alembic commands ###
