"""add credits and subscription system

Revision ID: 7dc38e7ab782
Revises: 1f87f09d1e41
Create Date: 2025-08-24 17:50:50.191318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc38e7ab782'
down_revision = '1f87f09d1e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 检查并添加credits列（如果不存在）
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    user_columns = [col['name'] for col in inspector.get_columns('user')]
    
    if 'credits' not in user_columns:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=True))
    
    # 检查并添加其他字段
    history_columns = [col['name'] for col in inspector.get_columns('history')]
    
    if 'sources_json' not in history_columns:
        with op.batch_alter_table('history', schema=None) as batch_op:
            batch_op.add_column(sa.Column('sources_json', sa.Text(), nullable=True))
    
    if 'timecodes_json' not in history_columns:
        with op.batch_alter_table('history', schema=None) as batch_op:
            batch_op.add_column(sa.Column('timecodes_json', sa.Text(), nullable=True))
    
    # 更新索引
    with op.batch_alter_table('user', schema=None) as batch_op:
        # 删除旧索引（如果存在）
        try:
            batch_op.drop_index('idx_users_email_unique')
        except:
            pass
        try:
            batch_op.drop_index('idx_users_phone_unique')
        except:
            pass
        
        # 创建新索引
        batch_op.create_index('ix_user_email', ['email'], unique=True)
        batch_op.create_index('ix_user_phone', ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_phone')
        batch_op.drop_index('ix_user_email')
        batch_op.create_index('idx_users_phone_unique', ['phone'], unique=1, sqlite_where=sa.text('phone IS NOT NULL'))
        batch_op.create_index('idx_users_email_unique', ['email'], unique=1, sqlite_where=sa.text('email IS NOT NULL'))
        batch_op.drop_column('credits')

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_column('sources_json')
        batch_op.drop_column('timecodes_json')
    # ### end Alembic commands ###
