"""add speech_onset_ms field to history table

Revision ID: add_speech_onset_ms
Revises: 7b27e4ed97cd
Create Date: 2025-09-15 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_speech_onset_ms'
down_revision = '7b27e4ed97cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('speech_onset_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'speech_onset_ms')
    # ### end Alembic commands ###
