"""Add original input fields to history table

Revision ID: add_original_input_fields
Revises: 7b27e4ed97cd
Create Date: 2025-01-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_original_input_fields'
down_revision = '7b27e4ed97cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_input', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('input_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_column('input_type')
        batch_op.drop_column('original_input')
    # ### end Alembic commands ###
